site_name: Government Platform as a Service documentation
theme: readthedocs
pages:
- Overview:
    - 'Government Platform as a Service (PaaS)': 'index.md'
    - 'Benefits of PaaS' : 'overview/benefits.md'
    - 'Technology' : 'overview/technology.md'
    - 'Pricing' : 'overview/pricing.md'
- Getting Started:
    - 'PaaS Requirements': 'getting_started/before_you_start.md'
    - 'Quick Setup Guide': 'getting_started/quick_setup_guide.md'
- Deploying Apps:
    - 'Deployment Guide': 'deploying_apps/index.md'
    - 'Excluding Files': 'deploying_apps/excluding_files.md'
    - 'Deploying a Static Site': 'deploying_apps/deploying_static_sites.md'
    - 'Deploying a Ruby on Rails App': 'deploying_apps/deploying_rails.md'
#    - 'Deploying Flask': 'deploying_apps/deploying_flask.md'
#    - 'Deploying Django': 'deploying_apps/deploying_django.md'
    - 'Deploying a Node.js App': 'deploying_apps/deploying_node_js.md'
    - 'Using Travis CI': 'deploying_apps/travis_ci.md'
    - 'Logging': 'deploying_apps/logging.md'
- Deploying Backing Services:
    - 'Services Overview': 'deploying_services/index.md'
    - 'Creating a PostgreSQL Service': 'deploying_services/postgres.md'
- Managing Apps:
    - 'Scaling Apps' : 'managing_apps/scaling.md'
    - 'Quotas': 'managing_apps/quotas.md'
    - 'Using Travis CI': 'managing_apps/travis_ci.md'
    - 'Redirecting All Traffic': 'managing_apps/redirect_all_traffic.md'
copyright: Found a mistake in this documentation? Or do you have a question it doesn't answer? Please email us at <a href="mailto:gov-uk-paas-support@digital.cabinet-office.gov.uk">gov-uk-paas-support@digital.cabinet-office.gov.uk</a>.
